apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: springboot 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot 
    spec:
      containers:
        - name: springboot 
          image: acrvvikash.azurecr.io/springboot
          ports:
          - containerPort: 8080