---
apiVersion: v1
kind: Service
metadata:
    name: springboot
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: springboot

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: springboot
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: springboot.vikash.dxc
    http:
      paths:
      - backend:
          serviceName: springboot
          servicePort: 80
        path: /hello
